// Generated by scripts/sync-door-definitions.mjs from Tiled.
export default {
  "school": [
    {
      "id": "bathroom-entry",
      "x": 384,
      "y": 224,
      "width": 32,
      "height": 32,
      "open": false,
      "locked": false,
      "interactive": true
    },
    {
      "id": "exit_main_door",
      "x": 352,
      "y": 384,
      "width": 64,
      "height": 32,
      "open": true,
      "locked": false,
      "interactive": false
    },
    {
      "id": "note-door-190",
      "x": 672,
      "y": 688,
      "width": 32,
      "height": 64,
      "open": false,
      "locked": false,
      "interactive": true
    },
    {
      "id": "note-door-192",
      "x": 576,
      "y": 752,
      "width": 64,
      "height": 32,
      "open": false,
      "locked": false,
      "interactive": true
    }
  ],
  "outside": [
    {
      "id": "school-main-entry",
      "x": 432,
      "y": 192,
      "width": 96,
      "height": 32,
      "open": true,
      "locked": false,
      "interactive": true
    }
  ]
};
